apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gotcp
  name: gotcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotcp
  template:
    metadata:
      labels:
        app: gotcp
    spec:
      containers:
      - image: farazf001/gotcp:latest
        name: gotcp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
