apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gotcp
  name: gotcp
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotcp
  template:
    metadata:
      labels:
        app: gotcp
    spec:
      containers:
      - image: farazf001/gotcp:1.0
        name: gotcp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gotcp
  name: gotcp
  namespace: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: gotcp
  type: NodePort
